underscores_in_headers on;
resolver 127.0.0.11 valid=10s ipv6=off;
resolver_timeout 5s;

server {
  listen 80;
  listen [::]:80;
  server_name rwagate.net www.rwagate.net api.rwagate.net admin.rwagate.net;
  client_max_body_size 50m;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  location / {
    return 404;
  }
}
