server {
  listen 80;
  listen [::]:80;
  server_name ${RWAT_ALL_DOMAINS};
  client_max_body_size 50m;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  location / {
    return 404;
  }
}
