server {
  listen 80;
  listen [::]:80;
  server_name ${RWAT_ALL_DOMAINS};
  client_max_body_size 50m;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name ${RWAT_FRONTEND_DOMAINS};
  client_max_body_size 50m;
  root ${RWAT_FRONTEND_ROOT};
  index index.html;

  ssl_certificate /etc/letsencrypt/live/${RWAT_CERT_NAME}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${RWAT_CERT_NAME}/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:RWATSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name ${RWAT_API_DOMAIN};
  client_max_body_size 50m;

  ssl_certificate /etc/letsencrypt/live/${RWAT_CERT_NAME}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${RWAT_CERT_NAME}/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:RWATSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass ${RWAT_API_UPSTREAM};
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name ${RWAT_ADMIN_DOMAIN};
  client_max_body_size 50m;

  ssl_certificate /etc/letsencrypt/live/${RWAT_CERT_NAME}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${RWAT_CERT_NAME}/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:RWATSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass ${RWAT_ADMIN_UPSTREAM};
  }
}
